manifest:
  defaults:
    revision: main

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: nxp-upstream
      url-base: https://github.com/nxp-upstream

    - name: nxp-pro-support
      url-base: https://github.com/nxp-pro-support

  defaults:
    remote: zephyrproject-rtos
    revision: main

  projects:

    - name: zephyr
      remote: zephyrproject-rtos
      repo-path: zephyr
      revision: main
      import: true

    - name: zephyr-module-sample
      remote: nxp-pro-support
      repo-path: zephyr-module-sample
      revision: main
      path: ./modules/module-sample

    - name: zephyr-custom-board-sample
      remote: nxp-pro-support
      repo-path: zephyr-custom-board-sample
      revision: main
      path: ./custom-boards/


  self:
    path: zephyr-start
    
