manifest:
  defaults:
    remote: zephyrproject-rtos
    revision: main

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: nxp-pro-support
      url-base: https://github.com/nxp-pro-support
      
    - name: wn
      url-base: https://github.com/wavenumber-eng

  projects:

    - name: zephyr
      remote: zephyrproject-rtos
      repo-path: zephyr
      revision: v4.3.0
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_nxp
          - liblc3
          - libmetal
          - littlefs
          - mbedtls
          - lvgl
          - open-amp
          - segger

    - name: zephyr-module-sample
      remote: nxp-pro-support
      repo-path: zephyr-module-sample
      revision: main
      path: ./modules/module-sample

    - name: zephyr-custom-board-sample
      remote: nxp-pro-support
      repo-path: zephyr-custom-board-sample
      revision: main
      path: ./custom-boards/
      
    - name: wn_zephyr_modules   
      remote: wn    
      path: ./modules/wn_modules     
      revision: main
     
    - name: bunny_build
      remote: wn
      revision: main
      path: modules/bunny_build
      

  self:
    path: app
    
