CONFIG_NET_TCP=y
CONFIG_APP_HTTP_SERVER=y

CONFIG_MAIN_STACK_SIZE=3584
CONFIG_HEAP_MEM_POOL_SIZE=6144

CONFIG_NET_PKT_RX_COUNT=10
CONFIG_NET_PKT_TX_COUNT=10
CONFIG_NET_BUF_RX_COUNT=32
CONFIG_NET_BUF_TX_COUNT=32
CONFIG_NET_MAX_CONTEXTS=8
